version: "3"
services:
  myportfolio:
    container_name: myportfolio
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - .:/myportfolio
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: example
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mydatabase: